/** Copy strings for the chat letter exchange feature. */
export const chatCopy = {
  tab: '笔谈',
  signatureUser: '我',
  signatureNight: '夜记',
  emptyTitle: (name: string) => (name ? `${name}，这一叠信还空着` : '这一叠信还空着'),
  emptyDesc: () => '写点什么，夜记在读',
  newConversation: '另起一封',
  inputPlaceholder: '回信……',
  sendLabel: '寄出',
  confirmDelete: '删掉这一叠信？',
  confirmDeleteDesc: '往来信件将一并删去，此操作不可撤销。',
  cancel: '取消',
  confirm: '确认删除',
  noReference: '暂无可附的日记',
  pickDiary: '附上日记',
  pickDiaryHint: '最多 3 篇日记 · 3 张卡片',
  pickDiaryEmpty: '暂无可附的日记',
  pickCardSection: '卡片',
  pickCardHint: '未关联日记的独立卡',
  pickCardEmpty: '暂无可附的卡片',
  removePin: '取下这一篇',
  removeCardPin: '取下这一张',
  pickPlan: '附上计划',
  pickPlanHint: '进行中的计划 · 最多 3 个',
  pickPlanEmpty: '暂无可附的计划',
  removePlanPin: '取下这一个',
  writingLabel: '夜记正在写…',
  letterNoteCount: (count: number) => `参考了 ${count} 篇日记`,
  letterAttachNote: (cards: number, plans: number) => {
    const parts: string[] = []
    if (cards > 0) parts.push(`${cards} 张卡片`)
    if (plans > 0) parts.push(`${plans} 个计划`)
    return parts.length ? `附上 ${parts.join('、')}` : ''
  },
  generateCard: '存为记忆卡片',
  cardGenerating: '收入中…',
  cardSavedInline: '已收入记忆',
  dateDivider: (date: string) => date,
  skillRecordLabel: '已录入日记',
  skillRecordExpand: '展开全文',
  skillRecordCollapse: '收起',
  skillInsightLabel: '洞悉 · 心理视角',
  skillPlanLabel: '已创建计划',
  skillPlanOpen: '去计划页推进',
  skillPlanCheckin: (days: number) => `坚持 ${days} 天 · 每日打卡`,
  skillPlanTimer: (hours: number) => `每日 ${hours} 小时 · 计时推进`,
  skillPlanNodes: (total: number, multiSource: number) =>
    `共 ${total} 个学习节点 · ${multiSource} 个有多来源候选`,
  skillHintTitle: '也可以直接吩咐夜记',
  skillHintRecord: '记一篇日记',
  skillHintInsight: '洞悉此刻的自己',
  skillHintPlan: '定一个小计划',
  skillPrefillRecord: '帮我记一篇日记：',
  skillPrefillInsight: '帮我分析一下：',
  skillPrefillPlan: '帮我做个计划：',
  skillModeAuto: '自动',
  skillModeRecord: '记录',
  skillModeInsight: '洞悉',
  skillModePlan: '计划',
  skillModeAutoTitle: '由夜记识别这封信的意图',
  skillModeRecordTitle: '把这封信转写成一篇日记',
  skillModeInsightTitle: '以心理视角分析这封信',
  skillModePlanTitle: '把这封信整理成一个计划',
  skillMenuHint: '输入 / 唤起技能 · ↑↓ 选择 · Enter 确认',
  skillMenuEmpty: '没有匹配的技能',
  /* ── 执行过程（process_info）：assistant 消息下的可折叠过程记录 ── */
  processLabel: '执行过程',
  processToggle: (skill: string | null | undefined, toolCount: number, seconds: number) => {
    const parts: string[] = []
    if (skill) parts.push(`${skill}技能`)
    if (toolCount > 0) parts.push(`${toolCount} 次工具调用`)
    if (seconds > 0) parts.push(`${seconds}s`)
    return parts.length ? `执行过程 · ${parts.join(' · ')}` : '执行过程'
  },
  processIntentLabel: '意图识别',
  processSkillLabel: '调用技能',
  processSkillManual: '手动选择',
  processSkillAuto: '自动识别',
  processToolsLabel: '工具调用',
  processToolSourceMcp: 'MCP',
  processToolSourceLocal: '内置',
  processRetrievalLabel: '上下文检索',
  processRetrievalDiaries: (n: number) => `日记 ${n} 篇`,
  processRetrievalMemories: (n: number) => `情景记忆 ${n} 条`,
  processDurationLabel: '总耗时',
  processTokensLabel: 'Token 用量',
} as const
