/** Copy strings for the chat letter exchange feature. */
export const chatCopy = {
  tab: '笔谈',
  signatureUser: '我',
  signatureNight: '夜记',
  emptyTitle: (name: string) => (name ? `${name}，这一叠信还空着` : '这一叠信还空着'),
  emptyDesc: () => '写点什么，夜记在读',
  newConversation: '另起一封',
  inputPlaceholder: '回信……',
  sendLabel: '寄出',
  confirmDelete: '删掉这一叠信？',
  confirmDeleteDesc: '往来信件将一并删去，此操作不可撤销。',
  cancel: '取消',
  confirm: '确认删除',
  noReference: '暂无可附的日记',
  pickDiary: '附上日记',
  pickDiaryHint: '最多 3 篇日记 · 3 张卡片',
  pickDiaryEmpty: '暂无可附的日记',
  pickCardSection: '卡片',
  pickCardHint: '未关联日记的独立卡',
  pickCardEmpty: '暂无可附的卡片',
  removePin: '取下这一篇',
  removeCardPin: '取下这一张',
  pickPlan: '附上计划',
  pickPlanHint: '进行中的计划 · 最多 3 个',
  pickPlanEmpty: '暂无可附的计划',
  removePlanPin: '取下这一个',
  writingLabel: '夜记正在写…',
  letterNoteCount: (count: number) => `参考了 ${count} 篇日记`,
  letterAttachNote: (cards: number, plans: number) => {
    const parts: string[] = []
    if (cards > 0) parts.push(`${cards} 张卡片`)
    if (plans > 0) parts.push(`${plans} 个计划`)
    return parts.length ? `附上 ${parts.join('、')}` : ''
  },
  generateCard: '存为记忆卡片',
  cardGenerating: '收入中…',
  cardSavedInline: '已收入记忆',
  dateDivider: (date: string) => date,
  skillRecordLabel: '已录入日记',
  skillRecordExpand: '展开全文',
  skillRecordCollapse: '收起',
  skillInsightLabel: '洞悉 · 心理视角',
  skillPlanLabel: '已创建计划',
  skillPlanOpen: '去计划页推进',
  skillPlanCheckin: (days: number) => `坚持 ${days} 天 · 每日打卡`,
  skillPlanTimer: (hours: number) => `每日 ${hours} 小时 · 计时推进`,
  skillPlanNodes: (total: number, verified: number) =>
    `共 ${total} 个学习节点 · ${verified} 个附参考链接`,
  skillHintTitle: '也可以直接吩咐夜记',
  skillHintRecord: '记一篇日记',
  skillHintInsight: '洞悉此刻的自己',
  skillHintPlan: '定一个小计划',
  skillPrefillRecord: '帮我记一篇日记：',
  skillPrefillInsight: '帮我分析一下：',
  skillPrefillPlan: '帮我做个计划：',
} as const
