/** Centralized copy for the plan scene. */

export const planCopy = {
  title: '我的计划',
  newPlan: '新建计划',
  plansEmpty: '还没有计划，可以从一个小目标开始',
  plansEmptyCta: '自己建一个',
  plansEmptyAiCta: '让 AI 帮规划',
  aiBadge: 'AI 建议',
  delete: '删除',
  refsLabel: '来自你的日记',
  formTitleLabel: '计划标题',
  formTitlePlaceholder: '比如：早睡挑战',
  formMotivationLabel: '为什么想做（可选）',
  formMotivationPlaceholder: '写下这个计划对你的意义……',
  formTasksLabel: '任务（可选，创建后还能加）',
  formTaskPlaceholder: '任务标题',
  formTaskDueLabel: '截止',
  formAddTask: '加一条任务',
  formRemoveTask: '移除',
  formSubmit: '创建计划',
  formCancel: '取消',
  pullToToday: '拉一条进今日待办',
  pullPlaceholder: '预填标题，可改……',
  pullSubmit: '添加',
  actualInputLabel: '实际值（可选）',
  actualConfirm: '确定',
  actualSkip: '跳过',
  recurrenceLabel: '周期',
  recurrenceNone: '无',
  recurrenceDaily: '每日',
  recurrenceWeekly: '每周',
  recurrenceWeekdays: '选择周几',
  targetValueLabel: '目标值（可选）',
  targetUnitPlaceholder: '单位，如 h、章',
  targetPeriodDaily: '每日',
  targetPeriodWeekly: '每周',
  targetPeriodTotal: '累计',
  archivedTitle: '已归档',
  expandPlan: '展开',
  /* 技能模板计划（PR8） */
  checkinAction: '打卡 +1',
  checkinTodayDone: '今日已打卡',
  checkinPlanDone: '计划已完成',
  timerStart: '开始计时',
  timerStop: '停止计时',
  timerDailyDone: '今日已达标',
  streakDays: (days: number) => `已坚持 ${days} 天`,
  timerCompleteTitle: (title: string) => `「${title}」今日已达标`,
  timerCompleteDesc: '今天的计时目标已完成。计时仍在继续，可随时手动停止。',
  timerCompleteClose: '好的',
  checkinFailed: '打卡失败，稍后再试',
  timerFailed: '计时操作失败，稍后再试',
  nodeReference: '参考',
} as const
