/** Centralized copy for the plan scene. */

export const planCopy = {
  title: '我的计划',
  newPlan: '新建计划',
  todayTitle: '今日待办',
  todayEmpty: '今天没有待办，享受当下吧',
  todayAddCta: '添加待办',
  todayAddPlaceholder: '记一条待办……',
  plansTitle: '计划',
  plansEmpty: '还没有计划，可以从一个小目标开始',
  plansEmptyCta: '自己建一个',
  plansEmptyAiCta: '让 AI 帮规划',
  aiBadge: 'AI 建议',
  delete: '删除',
  refsLabel: '来自你的日记',
  formTitleLabel: '计划标题',
  formTitlePlaceholder: '比如：早睡挑战',
  formMotivationLabel: '为什么想做（可选）',
  formMotivationPlaceholder: '写下这个计划对你的意义……',
  formTasksLabel: '任务（可选，创建后还能加）',
  formTaskPlaceholder: '任务标题',
  formTaskDueLabel: '截止',
  formAddTask: '加一条任务',
  formRemoveTask: '移除',
  formSubmit: '创建计划',
  formCancel: '取消',
} as const
