/** Unified timeline scene copy. Plain Chinese in .ts files is the established pattern (see weekly.ts). */

export const timelineCopy = {
  viewDay: '日',
  viewWeek: '周',
  viewMonth: '月',
  writeDiary: '记一笔',
  retry: '重试',
  prevDay: '前一天',
  nextDay: '后一天',
  prevWeek: '前一周',
  nextWeek: '后一周',
  todayTag: '今天',
  backToToday: '回到今天',
  emptyTitle: '这一天还没有记录',
  emptyHint: '从一句话开始就好',
  emptyCta: '记一笔',
  moreRecords: (n: number) => `还有 ${n} 条记录`,
  dayDrawerTitle: (label: string, day: number) => `${label} ${day}日`,
  taskSummary: (total: number, done: number) => `今日 ${total} 项 · 已完成 ${done}`,
  taskSectionDone: '都完成了，慢慢来',
  noLetterThisWeek: '这一周没有留下周信',
  planSectionTitle: '这一周的计划',
  fromDiary: (date?: string) => (date ? `来自 ${date} 的日记` : '来自日记'),
  aiSuggested: 'AI 建议',
  weekOverview: (diary: number, card: number, done: number, total: number) =>
    `${diary} 篇日记 · ${card} 张卡片 · 任务 ${done}/${total}`,
  detailReplyLabel: '回信',
  detailContinue: '继续编辑',
  detailViewReply: '查看回信',
  detailGetReply: '获取回信',
  detailExport: '导出 Markdown',
  detailDelete: '删除日记',
  detailDeleteConfirm: '确定删除这篇日记吗？',
  detailDeleteConfirmDesc: '删除后无法恢复，关联的记忆卡片不受影响',
  detailDeleteCancel: '取消',
  detailDeleteConfirmBtn: '确认删除',
} as const
